# Assets configuration
ASSETS_PATH_DIR = "assets"

ASSETS_PATH_IMAGE = ASSETS_PATH_DIR + "/pug.jpg"
ASSETS_PATH_VIDEO = ASSETS_PATH_DIR + "/puppy.mp4"

# Webcam configuration
DEFAULT_WEBCAM = 0

WIDTH_WEBCAM_ID = 3
WIDTH_WEBCAM_VALUE = 640

HEIGHT_WEBCAM_ID = 4
HEIGHT_WEBCAM_VALUE = 480

BRIGHTNESS_WEBCAM_ID = 10
BRIGHTNESS_WEBCAM_VALUE = 100